default:
  backend:
    host: localhost
    port: 8080

  caches:
  - name: content
    pattern: '/content'
  - name: app
    pattern: '.*'

  debug:
    logging:
      level: info
      showSensitive: false
      modules:
      - name: proxy/ws-client
        level: trace
        methods:
        # - name: backendClientOpts
        #   level: info
        - name: uplinkClientOpts
          level: info
  proxy:
    forwardHeaders:
    - content-type
    - content-length
    - location

  socket:
    ping:
      interval: 10000
      timeout: 1000

environment:
- name: moon
  config:
    backend:
      host: dev-direct.capnajax.moon
      port: 443
    security:
      insecure: false

- name: prod
  config:
    backend:
      host: prod-direct.capnajax.moon
      port: 443
    security:
      insecure: false
