default:
  backend:
    host: localhost
    port: 8080

  caches:
  - name: content
    pattern: '/content'
  - name: app
    pattern: '.*'

  debug:
    logging:
      level: info
      showSensitive: false
      modules:
      - name: proxy/ws-client
        level: trace
        methods:
        - name: clientPostProxy
          level: trace
        - name: uplinkClientOpts
          level: trace

  proxy:
    forwardHeaders: []

  socket:
    ping:
      interval: 10000
      timeout: 1000

environment:
- name: moon
  config:
    backend:
      host: capnajax-www
      port: 8080
    security:
      insecure: false
