default:
  backend:
    host: localhost
    port: 8080

  caches:
  - name: content
    pattern: '/content'
  - name: app
    pattern: '.*'

  debug:
    logging:
      level: info
      showSensitive: false
      modules:
      - name: proxy/server
        level: info
        methods:
        - name: dequeConnection
          level: trace
        - name: queueConnection
          level: debug
        - name: closeConnection
          level: debug
        - name: requestDocument
          level: trace

  proxy:
    forwardHeaders:
    - cache-control
    - content-type
    - content-length
    - location

  socket:
    ping:
      interval: 10000
      timeout: 1000

environment:
- name: moon
  config:
    backend:
      host: dev-direct.capnajax.moon
      port: 443
    security:
      insecure: false

- name: prod
  config:
    backend:
      host: direct.capnajax.moon
      port: 80
    security:
      insecure: false
