default:
  backend:
    baseUrl: http://localhost:8080

  caches:
  - name: content
    pattern: '/content'
  - name: app
    pattern: '.*'

  debug:
    logging:
      level: trace
      showSensitive: true

  socket:
    ping:
      interval: 10000
      timeout: 1000

environment:
- name: moon
  config:
    backend:
      baseUrl: https://capnajax.moon
    security:
      insecure: false
