default:
  backend:
    host: localhost
    port: 8080

  caches:
  - name: content
    pattern: '/content'
  - name: app
    pattern: '.*'

  debug:
    logging:
      level: info
      showSensitive: false

  proxy:
    forwardHeaders:
    - content-type
    - content-length

  socket:
    ping:
      interval: 10000
      timeout: 1000

environment:
- name: moon
  config:
    backend:
      host: capnajax-www
      port: 8080
    security:
      insecure: false
